routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes(['verify' => true]);

Route::group(['namespace' => 'Frontend'], function () {
    // home page
    Route::get('/', 'RoutingController@index')->name('home');


    // user management
    Route::get('/users/registration/{step}', 'User\AuthenticationController@registration')->name('users.registration');
    Route::post('/users/registration', 'User\AuthenticationController@register')->name('users.register');
    Route::get('/users/login', 'User\AuthenticationController@login')->name('users.login');
    Route::get('/users/forgot_password', 'User\AuthenticationController@forgot_password')->name('users.forgot_password');
    Route::post('/users/forgot_password/send', 'User\AuthenticationController@forgot_password_send')->name('users.forgot_password_send');
    Route::post('/users/reset_password', 'User\AuthenticationController@reset_password')->name('users.reset_password');
    Route::get('/users/create_password/{token}', 'User\AuthenticationController@create_password')->name('users.create_password');
    Route::post('/users/create_password', 'User\AuthenticationController@store_password')->name('users.store_password');

    // pages
    Route::get('/packages', 'RoutingController@packages')->name('packages');
    Route::get('/news', 'RoutingController@news')->name('news');
    Route::get('/news/{news}', 'RoutingController@news_detail')->name('news.detail');
    Route::get('/companies', 'RoutingController@companies')->name('companies');
    Route::get('/companies/{company}', 'RoutingController@company_detail')->name('companies.detail');
    Route::get('/events', 'RoutingController@events')->name('events');
    Route::get('/events/{event}', 'RoutingController@event_detail')->name('events.detail');
    Route::get('/job_offers', 'RoutingController@job_offers')->name('job_offers');
    Route::get('/job_offer/{job_offer}', 'RoutingController@job_offer_detail')->name('job_offer_detail');
    Route::get('/job_offer/{job_offer}/apply', 'RoutingController@job_offer_apply')->name('job_offer.apply');
    Route::post('/job_offer/{job_offer}/user_apply', 'RoutingController@job_offer_user_apply')->name('job_offer.user_apply');
    Route::get('/reservations', 'RoutingController@reservations')->name('reservations');
    Route::get('/booking/{location}/{date?}/{time?}', 'RoutingController@booking')->name('reservations.booking');
    Route::post('/booking/{location}', 'RoutingController@booking_store')->name('reservations.booking.store');
    Route::get('/booking_success/{location}/{booking}', 'RoutingController@booking_success')->name('reservations.booking.success');
    Route::get('/contacts', 'RoutingController@contacts')->name('contacts');
    Route::post('/contacts/store', 'RoutingController@contacts_store')->name('contacts.store');
    Route::get('/about', 'RoutingController@about')->name('about');
    Route::get('/coupon', 'RoutingController@coupon')->name('coupon');
    Route::get('/t_regalo', 'RoutingController@t_regalo')->name('tRegalo');
    Route::get('/t_regalo/buy', 'RoutingController@buy_t_regalo')->name('buy_t_regalo');
    Route::post('/t_regalo/buy', 'RoutingController@store_buy_t_regalo')->name('store_buy_t_regalo');

    // legal
    Route::get('/privacy_policy', 'RoutingController@privacy_policy')->name('privacy_policy');
    Route::get('/terms_and_conditions', 'RoutingController@terms_and_conditions')->name('terms_and_conditions');
    Route::get('/impressum', 'RoutingController@impressum')->name('impressum');



    Route::group(['middleware' => 'auth', 'prefix' => 'fx'], function () {
        // user profile
        Route::get('/users/profile/{edit?}', 'User\ProfileController@profile')->name('users.profile');
        Route::post('/users/delete/{user}', 'User\ProfileController@delete')->name('users.delete');
        Route::get('/users/tregalo', 'User\ProfileController@tregalo')->name('users.tregalo');
        Route::post('/users/profile/address/update', 'User\ProfileController@update_address')->name('users.update_address');
        Route::post('/users/profile/password/update', 'User\ProfileController@update_password')->name('users.update_password');
        Route::get('/users/cv', 'User\ProfileController@cv')->name('users.cv');
        Route::get('/users/cv/edit', 'User\ProfileController@cv_edit')->name('users.cv_edit');
        Route::post('/users/profile/update_profile', 'User\ProfileController@update_profile')->name('users.update_profile');
        Route::post('/users/profile/edit_avatar', 'User\ProfileController@edit_avatar')->name('users.edit_avatar');
        Route::get('/cv/add_widget', 'User\ProfileController@add_widget')->name('cv.add_widget');
        Route::post('/cv/edit_widget', 'User\ProfileController@edit_widget');
        Route::post('/cv/delete_widget', 'User\ProfileController@delete_widget');
        Route::get('/cv/add_social_widget', 'User\ProfileController@add_social_widget')->name('cv.add_social_widget');
        Route::post('/cv/edit_social_widget', 'User\ProfileController@edit_social_widget');
        Route::post('/cv/delete_social_widget', 'User\ProfileController@delete_social_widget');
        Route::get('/cv/add_experience_widget', 'User\ProfileController@add_experience_widget')->name('cv.add_experience_widget');
        Route::post('/cv/edit_experience_widget', 'User\ProfileController@edit_experience_widget');
        Route::post('/cv/delete_experience_widget', 'User\ProfileController@delete_experience_widget');
        Route::get('/cv/add_education_widget', 'User\ProfileController@add_education_widget')->name('cv.add_education_widget');
        Route::post('/cv/edit_education_widget', 'User\ProfileController@edit_education_widget');
        Route::post('/cv/delete_education_widget', 'User\ProfileController@delete_education_widget');
        Route::get('/cv/add_certificate_widget', 'User\ProfileController@add_certificate_widget')->name('cv.add_certificate_widget');
        Route::post('/cv/edit_certificate_widget', 'User\ProfileController@edit_certificate_widget');
        Route::post('/cv/delete_certificate_widget', 'User\ProfileController@delete_certificate_widget');
        Route::get('/cv/add_language_widget', 'User\ProfileController@add_language_widget')->name('cv.add_language_widget');
        Route::post('/cv/edit_language_widget', 'User\ProfileController@edit_language_widget');
        Route::post('/cv/delete_language_widget', 'User\ProfileController@delete_language_widget');
        Route::get('/cv/add_skill_widget', 'User\ProfileController@add_skill_widget')->name('cv.add_skill_widget');
        Route::post('/cv/edit_skill_widget', 'User\ProfileController@edit_skill_widget');
        Route::post('/cv/delete_skill_widget', 'User\ProfileController@delete_skill_widget');
        Route::get('/cv/add_hobby_widget', 'User\ProfileController@add_hobby_widget')->name('cv.add_hobby_widget');
        Route::post('/cv/edit_hobby_widget', 'User\ProfileController@edit_hobby_widget');
        Route::post('/cv/delete_hobby_widget', 'User\ProfileController@delete_hobby_widget');
        Route::post('/cv/edit_role_description', 'User\ProfileController@edit_role_description');
        Route::post('/cv/edit_description', 'User\ProfileController@edit_description');
        Route::get('/cv/change_cv_status/{status}', 'User\ProfileController@change_cv_status')->name('cv.change_status');
    });

});

Auth::routes();


Route::group(['middleware' => ['auth', 'internal_user'], 'prefix' => 'backend', 'namespace' => 'Backend'], function () {

    /* INTERNAL USERS ROUTES */

    Route::get('dashboard', 'DashboardController@index')->name('backend.dashboard');
    Route::get('/users/account/{subnav?}', 'UserAccountController@account')->name('backend.account');
    Route::post('/users/account', 'UserAccountController@update_account')->name('backend.update_account');
    Route::post('/users/account/avatar', 'UserAccountController@update_account_avatar')->name('backend.update_account_avatar');

    Route::get('/company/list', 'CompanyManagementController@index')->name('company_management.index');
    Route::get('/company/create', 'CompanyManagementController@create_company')->name('company_management.create');
    Route::post('/company/store', 'CompanyManagementController@store')->name('company_management.store');
    Route::get('/company/show/{company}', 'CompanyManagementController@show')->name('company_management.show');
    Route::get('/company/send_mail/{company}', 'CompanyManagementController@send_mail')->name('company_management.send_mail');
    Route::get('/company/update_status/{company}/{status}', 'CompanyManagementController@update_status')->name('company_management.update_status');

    Route::get('/inbox', 'InboxController@index')->name('backend.inbox');
    Route::post('/inbox/mark_all_as_read', 'InboxController@mark_all_as_read')->name('backend.inbox.mark_all_as_read');
    Route::post('/inbox/mark_as_read', 'InboxController@mark_as_read')->name('backend.inbox.mark_as_read');
    Route::post('/inbox/delete', 'InboxController@delete')->name('backend.inbox.delete');

    Route::get('/registered', 'UserController@registered')->name('backend.registered');

    Route::resources([
        'roles' => 'RoleController',
        'users' => 'UserController',
        'company_classifications' => 'CompanyClassificationController',
        'company_categories' => 'CompanyCategoryController',
        'company_statuses' => 'CompanyStatusController',
        'company_employees_count' => 'CompanyEmployeeCountController',
        'features' => 'FeatureController',
        'packages' => 'PackageController',

app/Role.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Role extends Model
{
    use SoftDeletes;

    protected $fillable = ['name', 'label', 'internal', 'parent_role_id'];

    protected $guarded = ['id'];

    public function parent_role()
    {
        return $this->belongsTo('App\Role', 'parent_role_id');
    }

    public function users()
    {
        return $this->hasMany('App\User', 'role_id');
    }
}

app/Http/Controllers/Api/CompanyController.php
<?php

namespace App\Http\Controllers\Api;

use App\Company;
use App\CompanyCategory;
use App\CompanyClassification;
use App\CompanyStatus;
use App\District;
use App\Http\Controllers\Controller;
use App\Http\Resources\CompanyResource;
use App\Rating;
use App\UserCompanyFollower;
use App\UserCompanyRating;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use function foo\func;

class CompanyController extends Controller
{
    public function companies()
    {
        return response()->json(
            CompanyResource::collection(
                Company::where('status_id', CompanyStatus::where('active', 1)->first()->id)->orderBy('name')->get()
            )
        );
    }

    public function company(Company $company)
    {
        return response()->json(CompanyResource::make($company));
    }

    public function companies_filter(Request $request)
    {
        $companies = Company::query();
        $companies->where('status_id', CompanyStatus::where('active', 1)->first()->id);
        $companies->when($request->catFilter != null, function ($q) use ($request) {
            return $q->where('category_id', CompanyCategory::where('name', $request->catFilter)->first()->id);
        });
        $companies->when($request->filter != null, function ($q) use ($request) {
            return $q->where('name', 'LIKE', '%' . $request->filter . '%');
        });
        $companies->when($request->district != null, function ($q) use ($request) {
            return $q->where('district_id', District::where('name', $request->district)->first()->id);
        });

        return response()->json(CompanyResource::collection($companies->orderBy('name')->get()));
    }

    public function company_categories()
    {
        return response()->json(CompanyCategory::all()->pluck('name'));
    }

    public function company_districts()
    {
        return response()->json(District::all()->pluck('name'));
    }

    public function company_classifications()
    {
        return response()->json(CompanyClassification::all()->pluck('name'));
    }

    public function edit(Request $request, Company $company)
    {
        $this->validate($request, [
            'name' => 'required|string',
            'email' => 'required|email',
            'phone' => 'required',
        ]);

        $request->merge([
            'category_id' => CompanyCategory::where('name', $request->category)->first()->id,
            'classification_id' => CompanyClassification::where('name', $request->classification)->first()->id,
            'district_id' => District::where('name', $request->district)->first()->id,
        ]);

        $company->update($request->all());

        return;
    }

    public function edit_logo(Request $request, Company $company)
    {
        $file = $request->file('file')->store($company->id . '/logo', 'company');

        $company->update(['logo' => 'storage/company/' . $file]);

        return;
    }

    public function ratings(Request $request)
    {
        $rating = UserCompanyRating::where([
            'user_id' => $request->user,
            'company_id' => $request->company
        ])->first();

        if (empty($rating)) {
            return response()->json(['rating' => Rating::orderBy('rate')->get(), 'rate' => 0]);
        } else {
            return response()->json(['rating' => Rating::orderBy('rate')->get(), 'rate' => $rating->rating->rate]);
        }

    }

    public function rate_company(Request $request)
    {
        UserCompanyRating::where(['user_id' => $request->user, 'company_id' => $request->company])->delete();
        $rating = UserCompanyRating::create(['user_id' => $request->user, 'company_id' => $request->company, 'rating_id' => $request->rating]);
        $this->updateCompanyAverage($rating->company);
        return response()->json($rating);
    }

    public function follow_company(Request $request)
    {
        UserCompanyFollower::create(['user_id' => $request->user, 'company_id' => $request->company]);
        return response()->json();
    }

    public function unfollow_company(Request $request)
    {
        UserCompanyFollower::where(['user_id' => $request->user, 'company_id' => $request->company])->delete();
        return response()->json();
    }

    public function updateCompanyAverage(Company $company)
    {
        /**
         *** imdb rating ***
         *  (WR) = (v ÷ (v+m)) × R + (m ÷ (v+m)) × C
         *  R = average for the movie (mean) = (Rating)
         *  v = number of votes for the movie = (votes)
         *  m = minimum votes required to be listed in the Top 250 (currently 25000)
         *  C = the mean vote across the whole report (currently 7.1)
         **/
        $R = $company->ratings()->avg('rating_id');
        $v = $company->ratings()->count();
        $m = 10;
        $C = 3.8;

        $wr = ($v / ($v+$m)) * $R + ($m / ($v+$m)) * $C;
        $company->update(['avg_rating' => $wr]);
    }
}

app/Http/Controllers/Backend/RoleController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Http\Controllers\Controller;
use App\Http\Requests\CreateRoleRequest;
use App\Http\Requests\UpdateRoleRequest;
use App\Role;
use Illuminate\Http\Request;

class RoleController extends Controller
{

    public function index()
    {
        return view('backend.roles.index', ['roles' => Role::all()]);
    }

    public function create()
    {
        return view('backend.roles.create_edit');
    }

    public function store(CreateRoleRequest $request)
    {
        $request->request->add(['internal' => true]);
        Role::create($request->all());
        return redirect()->route('roles.index');
    }

    public function edit(Role $role)
    {
        return view('backend.roles.create_edit', ['role' => $role]);
    }

    public function update(Role $role, UpdateRoleRequest $request)
    {
        $role->update($request->all());
        return redirect()->route('roles.index');
    }

    public function destroy(Role $role)
    {
        $role->delete();
        return redirect()->back()->withErrors(['alert-success' => trans('backend/roles.delete', ['role' => $role->name])]);
    }


}

resources/views/company/roles/create_edit.blade.php
@extends('layouts.company.backend')

@section('content')
    <div class="page-header page-header-dark bg-gradient-primary-to-secondary">
        <div class="container-fluid">
            <div class="page-header-content py-5">
                <h1 class="page-header-title">
                    <div class="page-header-icon">
                        <i data-feather="link"></i>
                    </div>
                    @if(isset($company_sub_role))
                        <span>Modifica ruolo</span>
                    @else
                        <span>Crea un nuovo ruolo</span>
                    @endif
                </h1>
            </div>
        </div>
    </div>
    <div class="container-fluid mt-4">
        <div class="card mb-4 card-header-actions">
            <div class="card-header">
                @if(isset($company_sub_role))
                    <span>Modifica</span>
                @else
                    <span>Crea</span>
                @endif
                <div class="dropdown">
                    <a href="{{ route('company.roles.index', ['company' => $company->id]) }}"
                       class="btn btn-primary btn-icon btn-sm">
                        <i data-feather="skip-back"></i>
                    </a>
                </div>
            </div>
            <div class="card-body">
                @if(isset($company_sub_role))
                    <form
                        action="{{ route('company.roles.update', ['company' => $company->id, 'company_sub_role' => $company_sub_role->id]) }}"
                        method="post">
                        @else
                            <form action="{{ route('company.roles.store', ['company' => $company->id]) }}"
                                  method="post">
                                @endif
                                @csrf
                                <div class="form-group">
                                    <label for="role_name">Nome ruolo</label>
                                    <input class="form-control @error('name') is-invalid @enderror" name="name"
                                           type="text"
                                           value="{{ isset($company_sub_role) ? $company_sub_role->name : old('name') }}"/>
                                    @error('name')
                                    <span class="text-danger">{{ $message }}</span>
                                    @enderror
                                </div>
                                <label>Scegli i permessi disponibili nel tuo pacchetto</label><br>
                                @foreach($company->packages->first()->features as $feature)
                                    <b>{{ $feature->name }}</b>:<br>

                                    @foreach($feature->permissions as $permission)
                                        <div class="custom-control custom-checkbox custom-control-solid">
                                            <input class="custom-control-input"
                                                   id="{{ $permission->permission->label }}" name="permissions[]"
                                                   value="{{$permission->permission->id}}"
                                                   {{ isset($company_sub_role) ? collect($company_sub_role->permissions)->pluck('permission_id')->contains($permission->permission->id) ? 'checked' : '' : ''}}
                                                   type="checkbox">
                                            <label class="custom-control-label"
                                                   for="{{ $permission->permission->label }}">
                                                {{ $permission->permission->name }}
                                            </label>
                                        </div>
                                    @endforeach
                                    <br>
                                @endforeach

                                <div class="form-group">
                                    <input type="submit" class="btn btn-primary"
                                           value="{{ isset($feature) ? trans('general.update') : trans('general.save') }}">
                                </div>
                            </form>
            </div>
        </div>
    </div>
@endsection

resources/views/company/roles/index.blade.php
@extends('layouts.company.backend')

@section('content')
    <div class="page-header page-header-dark bg-gradient-primary-to-secondary">
        <div class="container-fluid">
            <div class="page-header-content py-5">
                <h1 class="page-header-title">
                    <div class="page-header-icon"><i data-feather="bar-chart-2"></i></div>
                    <span>Crea ruoli e assegnaci dei privilegi</span>
                </h1>
            </div>
        </div>
    </div>
    <div class="container-fluid mt-4">
        <div class="card mb-4 card-header-actions">
            <div class="card-header">
                Creazione dei ruoli
                <div class="dropdown">
                    <a href="{{ route('company.roles.create', ['company' => $company->id]) }}"
                       class="btn btn-primary btn-icon btn-sm">
                        <i data-feather="plus"></i>
                    </a>
                </div>
            </div>
            <div class="card-body">
                @error('alert-success')
                <div class="alert alert-primary" role="alert">{{ $message }}</div>
                @enderror
                <div class="datatable table-responsive">
                    <table class="table table-bordered table-hover" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Ruolo</th>
                            <th>Label</th>
                            <th>Permessi</th>
                            <th>{{ trans('general.tb_actions') }}</th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Ruolo</th>
                            <th>Label</th>
                            <th>Permessi</th>
                            <th>{{ trans('general.tb_actions') }}</th>
                        </tr>
                        </tfoot>
                        <tbody>
                        @forelse($company->roles as $role)
                            <tr>
                                <td>{{ $role->name }}</td>
                                <td>{{ $role->label }}</td>
                                <td>
                                    @foreach($role->permissions as $permission)
                                        <span class="badge badge-primary">{{ $permission->permission }}</span>
                                    @endforeach
                                </td>
                                <td>

                                    <a href="{{ route('company.roles.edit', ['company' => $company->id, 'company_sub_role' => $role->id]) }}"
                                       class="btn btn-datatable btn-icon btn-transparent-dark mr-2">
                                        <i data-feather="edit"></i>
                                    </a>
                                    <a class="btn btn-datatable btn-icon btn-transparent-dark"
                                       onclick="event.preventDefault();
                                           document.getElementById('trash-form-{{ $role->id }}').submit();">
                                        <i data-feather="trash-2"></i>
                                    </a>
                                    <form id="trash-form-{{ $role->id }}"
                                          action="{{ route('company.roles.delete', ['company' => $company->id, 'company_sub_role' => $role->id]) }}"
                                          method="post"
                                          style="display: none;">
                                        @method('DELETE')
                                        @csrf
                                    </form>
                                </td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="4" class="bg-gradient-primary-to-secondary text-white">
                                    {{ trans('backend/features.empty') }}
                                </td>
                            </tr>
                        @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
@endsection